import streamlit as st
import pandas as pd
import numpy as np
import joblib
import smtplib
from email.message import EmailMessage
from tensorflow.keras.models import load_model

# --- 1. CONFIG & ASSETS LOADING ---
st.set_page_config(page_title="Clinical AI Portal", layout="wide", page_icon="🏥")

@st.cache_resource
def load_ml_assets():
    """Loads the Deep Learning model and its pre-processing scalers."""
    try:
        model = load_model("model/model.h5")
        scaler = joblib.load("scaler.pkl")
        le = joblib.load("label_encoder.pkl")
        return model, scaler, le
    except Exception as e:
        st.warning(f"ML Assets (model.h5/scaler.pkl) not found: {e}")
        return None, None, None

@st.cache_data
def load_knowledge_bases():
    """Loads your specific CSV datasets for symptoms and drug descriptions."""
    try:
        # Load Disease and Symptoms
        disease_df = pd.read_csv('DiseaseAndSymptoms.csv')
        # Load Medicine Descriptions
        medicine_db = pd.read_csv('Medicine_description.xlsx')
        
        # Build a searchable map: {Disease: {symptom1, symptom2}}
        disease_map = {}
        for _, row in disease_df.iterrows():
            d = str(row['Disease']).strip()
            # Clean underscores from CSV to match user natural typing
            s = [str(val).strip().lower().replace("_", " ") for val in row[1:] if pd.notna(val)]
            if d not in disease_map:
                disease_map[d] = set(s)
            else:
                disease_map[d].update(s)
        return disease_map, medicine_db
    except Exception as e:
        st.error(f"CSV Database Error: {e}")
        return {}, pd.DataFrame()

# Global Initialization
model, scaler, le = load_ml_assets()
disease_map, medicine_db = load_knowledge_bases()

# --- 2. CORE LOGIC FUNCTIONS ---

def predict_from_symptoms(input_text):
    """Matches user symptoms against the 4,920 patterns in DiseaseAndSymptoms.csv."""
    if not input_text: return None, 0
    user_symptoms = [s.strip().lower() for s in input_text.split(",")]
    scores = {disease: len(set(user_symptoms).intersection(s_set)) 
              for disease, s_set in disease_map.items()}
    best_match = max(scores, key=scores.get, default=None)
    return (best_match, scores[best_match]) if scores.get(best_match, 0) > 0 else (None, 0)

def get_medication_recs(disease_name):
    """Looks up the 22,481 medicine records by the 'Reason' column."""
    if not disease_name or medicine_db.empty: return []
    # Partial match for "Allergy" vs "Allergies"
    mask = medicine_db['Reason'].str.contains(disease_name[:5], case=False, na=False)
    return medicine_db[mask][['Drug_Name', 'Description']].head(5).to_dict('records')

def create_html_report(data):
    """Generates the downloadable Clinical AI Diagnostic Report."""
    reasons_html = "".join([f"<li>{r}</li>" for r in data['reasons']])
    return f"""
    <div style="font-family: sans-serif; border: 2px solid #1a73e8; padding: 20px;">
        <h1 style="color: #1a73e8;">Clinical AI Diagnostic Report</h1>
        <hr>
        <p><b>Patient:</b> {data['name']} | <b>Age:</b> {data['age']}</p>
        <p><b>Diagnosis:</b> {data['disease']} ({data['prob']}%)</p>
        <p><b>Urgency:</b> {data['urgency']}</p>
        <h3>AI Reasoning:</h3>
        <ul>{reasons_html}</ul>
        <h3>Recommended Medications:</h3>
        <p>{data['meds']}</p>
        <footer style="margin-top:20px; font-size: 10px;">Generated by Onkar Wagh Clinical AI System 2026</footer>
    </div>
    """

# --- 3. USER INTERFACE ---

col_l, col_r = st.columns([1, 1])

with col_l:
    st.subheader("👤 Patient Identity & Vitals")
    p_name = st.text_input("Full Name")
    p_email = st.text_input("Doctor Email (Optional)")
    p_age = st.number_input("Age", 1, 120, 30)
    
    # Grid for Vitals
    v1, v2 = st.columns(2)
    hr = v1.number_input("Heart Rate", value=72.0)
    spo2 = v2.number_input("SpO2 %", value=98.0)
    bps = v1.number_input("BP Systolic", value=120.0)
    temp = v2.number_input("Temp °C", value=37.0)

with col_r:
    st.subheader("📋 Symptom-Based Therapy")
    symptoms_input = st.text_area("Enter Symptoms", placeholder="e.g. skin rash, itching, nodal skin eruptions")
    
    if st.button("Generate Therapy Recommendation", use_container_width=True):
        res_disease, res_score = predict_from_symptoms(symptoms_input)
        if res_disease:
            st.success(f"**Condition Detected:** {res_disease}")
            meds = get_medication_recs(res_disease)
            if meds:
                for m in meds:
                    with st.expander(f"💊 {m['Drug_Name']}"):
                        st.write(m['Description'])
            else:
                st.warning("No drugs found for this condition in Medicine_description database.")
        else:
            st.error("No matching condition found. Check symptom spelling.")

# --- 4. THE DUAL-ENGINE EXECUTION ---
st.divider()
if st.button("RUN FULL CLINICAL RISK DIAGNOSTIC", type="primary", use_container_width=True):
    if model and scaler:
        # 1. AI Prediction
        # Inputs: Age, HR, BP_Sys, BP_Dia, SpO2, Temp, Chol, Gluc, Resp
        raw_vitals = [p_age, hr, bps, 80.0, spo2, temp, 190.0, 95.0, 16.0]
        scaled = scaler.transform([raw_vitals])
        pred = model.predict(scaled, verbose=0)
        idx = np.argmax(pred)
        disease = le.inverse_transform([idx])[0]
        prob = pred[0][idx] * 100
        
        # 2. Logic Overrides (Triage)
        urgency = "High" if spo2 < 90 or bps > 175 else "Stable"
        
        # 3. Display Results
        st.header(f"AI Diagnosis: {disease}")
        st.metric("Confidence Score", f"{prob:.2f}%", delta=urgency)
        
        # 4. Export Data
        report_payload = {
            'name': p_name if p_name else "Unknown",
            'age': p_age,
            'disease': disease,
            'prob': f"{prob:.2f}",
            'urgency': urgency,
            'reasons': [f"Vitals: HR={hr}, SpO2={spo2}", f"Risk Level: {urgency}"],
            'meds': "See Full Dashboard for list"
        }
        
        html_doc = create_html_report(report_payload)
        st.download_button("📩 Download PDF/HTML Report", data=html_doc, file_name="Clinical_Report.html")
    else:
        st.error("Critical Failure: model.h5 or scaler.pkl is missing from the directory.")
