import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from tensorflow.keras.models import load_model
import joblib
import smtplib
from email.message import EmailMessage

# --- 1. CORE CLINICAL FUNCTIONS (Defined first to avoid NameErrors) ---

def create_clinical_report(report, reasons, warnings):
    """Generates a professional HTML diagnostic report for physician review."""
    return f"""
    <div style='font-family:Arial; border:2px solid #333; padding:20px; border-radius:10px;'>
        <h1 style='color:#1a73e8; text-align:center;'>Clinical AI Diagnostic Report</h1>
        <hr>
        <p><b>Patient:</b> {report['Name']} | <b>Age:</b> {report['Age']} | <b>Gender:</b> {report['Gender']}</p>
        <div style='background:#f0f2f6; padding:15px; border-radius:10px;'>
            <h3 style='margin:0;'>Primary Diagnostic: {report['Disease']}</h3>
            <p style='color:#d93025; font-weight:bold;'>Triage Status: {report['Risk']}</p>
            <p>Confidence Level: {report['Prob']}%</p>
        </div>
        <h4>📊 Physiological Analysis</h4>
        <ul>{"".join([f"<li>{r}</li>" for r in reasons])}</ul>
        <h4>💊 Safety Alerts</h4>
        <ul>{"".join([f"<li>⚠️ {w}</li>" for w in warnings]) if warnings else "<li>No acute drug-vital risks flagged.</li>"}</ul>
        <p><b>Next Steps:</b> {report['Urgency']}</p>
        <hr>
        <p style='font-size:10px; color:gray;'>Generated by Clinical AI CDSS. This report is a decision support tool and requires MD validation.</p>
    </div>
    """

def send_to_physician(receiver, report, reasons):
    """Handles secure SMTP transmission to the physician."""
    msg = EmailMessage()
    msg['Subject'] = f"🚨 {report['Risk']} Clinical Alert - {report['Name']}"
    msg['From'] = st.secrets.get("EMAIL_USER", "")
    msg['To'] = receiver
    
    body = f"""OFFICIAL CLINICAL HANDOVER
-------------------------------
PATIENT: {report['Name']} ({report['Age']}yr {report['Gender']})
PRIMARY PREDICTION: {report['Disease']} ({report['Prob']}%)
TRIAGE CATEGORY: {report['Risk']}

VITAL SIGNS ANALYSIS:
{chr(10).join(['- ' + r for r in reasons])}

This patient data was processed via the Clinical AI CDSS.
-------------------------------
"""
    msg.set_content(body)
    try:
        with smtplib.SMTP_SSL('smtp.gmail.com', 465) as smtp:
            smtp.login(st.secrets["EMAIL_USER"], st.secrets["EMAIL_PASS"])
            smtp.send_message(msg)
        return True
    except:
        return False

def get_triage_status(disease, prob, spo2, bps):
    """Advanced Triage Logic: Combines AI probability with physiological safety limits."""
    if spo2 < 88 or bps > 185 or (disease != "Normal" and prob > 94):
        return "🔴 CRITICAL", "Immediate Physician Intervention Required", "#ff4b4b"
    elif prob > 70 or spo2 < 93:
        return "🟡 URGENT", "Priority Nursing Assessment Required", "#ffa500"
    else:
        return "🟢 STABLE", "Routine Monitoring & Follow-up", "#28a745"

# --- 2. DATA & ASSET LOADING (Resilient Design) ---

@st.cache_data
def load_clinical_data():
    # Load Disease Knowledge
    disease_df = pd.read_csv('DiseaseAndSymptoms.csv')
    disease_df['Disease'] = disease_df['Disease'].astype(str).str.strip().str.title()
    
    # Load Medicine Knowledge (Handling your 'res' column)
    try:
        med_df = pd.read_csv('Medicine_description.xlsx', sep=None, engine='python', encoding='latin1')
        med_df.columns = [col.strip().replace('ï»¿', '') for col in med_df.columns]
        
        # Mapping your 'res' column to 'Reason' internally
        if 'res' in med_df.columns:
            med_df = med_df.rename(columns={'res': 'Reason'})
        elif 'Reason' in med_df.columns:
            pass
        else:
            med_df = med_df.rename(columns={med_df.columns[1]: 'Reason'})
            
        med_df['Reason'] = med_df['Reason'].fillna('Unknown').astype(str).str.strip().str.title()
    except:
        med_df = pd.DataFrame(columns=['Drug_Name', 'Reason', 'Description'])
    return disease_df, med_df

@st.cache_resource
def load_ml_assets():
    model = load_model("model/model.h5")
    scaler = joblib.load("scaler.pkl")
    label_encoder = joblib.load("label_encoder.pkl")
    return model, scaler, label_encoder

# Global Assets
model, scaler, label_encoder = load_ml_assets()
disease_db, med_db = load_clinical_data()

# Logic imports
try:
    from drug_module import check_drugs
    from explain import explain_values
except ImportError:
    st.error("Missing logic modules (drug_module.py or explain.py).")

# --- 3. UI DASHBOARD ---

st.set_page_config(page_title="Advanced CDSS", layout="wide")
st.title("🛡️ Enterprise Clinical Decision Support System")
st.caption("Integrated Neural Network Prediction + 22,000 Record Pharmacological Database")

c1, c2 = st.columns([1, 1.2])

with c1:
    st.subheader("👤 Patient Identity")
    p_name = st.text_input("Patient Full Name", placeholder="e.g. John Smith")
    doc_email = st.text_input("Physician Email for Handover")
    p_gender = st.selectbox("Gender", ["Male", "Female", "Other"])
    p_age = st.number_input("Age", 1, 120, 30)
    
    st.subheader("📉 Clinical Vitals")
    v1, v2, v3 = st.columns(3)
    hr = v1.number_input("Heart Rate", value=72.0)
    bps = v1.number_input("BP Systolic", value=120.0)
    spo2 = v2.number_input("SpO2 %", value=98.0)
    bpd = v2.number_input("BP Diastolic", value=80.0)
    temp = v3.number_input("Temp °C", value=37.0)
    gluc = v3.number_input("Glucose", value=95.0)

with c2:
    st.subheader("🧪 Clinical Context")
    curr_syms = st.text_area("Patient Reported Symptoms (e.g. skin_rash, chills, cough)")
    curr_meds = st.text_area("Current Medications (comma separated)")
    curr_allergies = st.text_area("Known Allergies")
    
    st.info("💡 Tip: If vitals are normal but you see skin issues, the AI will prioritize your symptoms in the final report.")

# --- 4. THE EXECUTION ENGINE ---

st.divider()
if st.button("🚀 EXECUTE MULTIMODAL DIAGNOSTIC SCAN", type="primary", width="stretch"):
    # 1. Neural Network Prediction
    # Order: [age, hr, bps, bpd, spo2, temp, chol, gluc, resp]
    raw_vitals = [p_age, hr, bps, bpd, spo2, temp, 190.0, gluc, 16.0] 
    scaled_vitals = scaler.transform(pd.DataFrame([raw_vitals], columns=scaler.feature_names_in_))
    prediction = model.predict(scaled_vitals, verbose=0)
    
    idx = np.argmax(prediction)
    disease = label_encoder.inverse_transform([idx])[0]
    prob = prediction[0][idx] * 100

    # 2. Heuristic Override (The "Weightage" Feature)
    # If vitals are normal but clear symptoms like Acne are present, we adjust the focus
    symptom_list = curr_syms.lower()
    if "pimple" in symptom_list or "skin_rash" in symptom_list or "acne" in symptom_list:
        if disease == "Normal":
            disease = "Acne / Skin Condition"
            prob = 98.5  # High confidence based on direct symptom matching

    # 3. Status & Logic
    status, action, color = get_triage_status(disease, prob, spo2, bps)
    reasons = explain_values(hr, (bps+bpd)/2, spo2, temp)
    warnings, _ = check_drugs(curr_meds.split(","), curr_syms.split(","), curr_allergies.split(","))

    # Display Triage Badge
    st.markdown(f"<div style='background:{color}; padding:20px; border-radius:10px; color:white; text-align:center;'><h1>{status}: {disease.upper()}</h1><p>{action}</p></div>", unsafe_allow_html=True)

    tab1, tab2, tab3 = st.tabs(["📊 Clinical Analytics", "💊 Pharmaceutical Pathway", "📄 Physician Handover"])
    
    with tab1:
        g1, g2 = st.columns([1.3, 1])
        with g1:
            st.markdown("#### Differential Diagnosis (AI Confidence)")
            conf_df = pd.DataFrame({"Condition": label_encoder.classes_, "Prob": prediction[0]*100}).sort_values("Prob", ascending=True)
            st.plotly_chart(px.bar(conf_df, x="Prob", y="Condition", orientation='h', color="Prob", color_continuous_scale="Reds", template="plotly_dark"), width="stretch")
        with g2:
            st.markdown("#### Physiological Radar Fingerprint")
            radar_cats = ['HR', 'SpO2', 'BP Sys', 'Temp', 'Glucose']
            radar_vals = [min(hr/160, 1.0), (100-spo2)/20, min(bps/200, 1.0), min(abs(temp-37)/5, 1.0), min(gluc/400, 1.0)]
            fig_radar = go.Figure(data=go.Scatterpolar(r=radar_vals, theta=radar_cats, fill='toself', line_color=color))
            fig_radar.update_layout(template="plotly_dark", polar=dict(radialaxis=dict(visible=False)))
            st.plotly_chart(fig_radar, width="stretch")

    with tab2:
        st.subheader(f"Therapeutic Database: {disease}")
        # Searching the 22,000 records using the standardized 'Reason' column
        search_term = "Acne" if "Acne" in disease else disease
        rel_meds = med_db[med_db['Reason'].str.contains(search_term, case=False, na=False)].head(10)
        
        if not rel_meds.empty:
            for _, row in rel_meds.iterrows():
                with st.expander(f"💊 {row['Drug_Name']}"):
                    st.write(f"**Indication:** {row['Reason']}")
                    st.write(f"**Description:** {row['Description']}")
        else:
            st.warning("No specific pharmaceutical records match this profile in the local database.")

    with tab3:
        report_data = {"Name": p_name, "Age": p_age, "Gender": p_gender, "Disease": disease, "Prob": round(prob, 2), "Risk": status, "Urgency": action}
        html_report = create_clinical_report(report_data, reasons, warnings)
        
        cdl, cem = st.columns(2)
        with cdl:
            st.download_button("📥 Download Official Report (HTML)", html_report, file_name=f"Report_{p_name}.html", mime="text/html", width="stretch")
        with cem:
            if doc_email and st.button("📧 Email Physician Now", width="stretch"):
                if send_to_physician(doc_email, report_data, reasons):
                    st.success(f"Clinical alert transmitted to {doc_email} ✅")
                else:
                    st.error("Email failed. Ensure EMAIL_USER/PASS are set in Secrets.")
